<a href="https://colab.research.google.com/github/sageradh1/1Logistic-Regression/blob/master/1Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [0]:
!wget https://raw.githubusercontent.com/susanli2016/Machine-Learning-with-Python/master/diabetes.csv

--2019-06-15 08:05:42--  https://raw.githubusercontent.com/susanli2016/Machine-Learning-with-Python/master/diabetes.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23875 (23K) [text/plain]
Saving to: ‘diabetes.csv’

diabetes.csv        100%[===================>]  23.32K  --.-KB/s    in 0.01s   

2019-06-15 08:05:42 (2.34 MB/s) - ‘diabetes.csv’ saved [23875/23875]



In [0]:
dataset = pd.read_csv("diabetes.csv")

In [0]:
dataset.head()


Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
features = dataset.drop(["Outcome"], axis=1)

In [0]:
features.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [0]:
X = np.array(features)

In [0]:
X


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [0]:
y = np.array(dataset["Outcome"])

In [0]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [0]:
X[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [0]:
X[:]

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [0]:
X[:2]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ]])

In [0]:
X = (X - np.min(X)) / (np.max(X) - np.min(X))

In [0]:
X #normalised dataset

array([[0.0070922 , 0.1749409 , 0.08510638, ..., 0.03971631, 0.00074113,
        0.05910165],
       [0.00118203, 0.10047281, 0.07801418, ..., 0.03144208, 0.00041489,
        0.03664303],
       [0.00945626, 0.21631206, 0.07565012, ..., 0.02754137, 0.00079433,
        0.03782506],
       ...,
       [0.00591017, 0.143026  , 0.08510638, ..., 0.03096927, 0.0002896 ,
        0.03546099],
       [0.00118203, 0.14893617, 0.07092199, ..., 0.0355792 , 0.00041253,
        0.05555556],
       [0.00118203, 0.10992908, 0.08274232, ..., 0.03593381, 0.00037234,
        0.02718676]])

In [0]:
X.shape

(768, 8)

In [0]:
def sigmoid(z):
   return 1 / (1 + np.exp(-z))

In [0]:
X.T #tranpose

array([[0.0070922 , 0.00118203, 0.00945626, ..., 0.00591017, 0.00118203,
        0.00118203],
       [0.1749409 , 0.10047281, 0.21631206, ..., 0.143026  , 0.14893617,
        0.10992908],
       [0.08510638, 0.07801418, 0.07565012, ..., 0.08510638, 0.07092199,
        0.08274232],
       ...,
       [0.03971631, 0.03144208, 0.02754137, ..., 0.03096927, 0.0355792 ,
        0.03593381],
       [0.00074113, 0.00041489, 0.00079433, ..., 0.0002896 , 0.00041253,
        0.00037234],
       [0.05910165, 0.03664303, 0.03782506, ..., 0.03546099, 0.05555556,
        0.02718676]])

In [0]:
def forward_propagation(W, b, X, y):
  data_number = X.shape[0]
  Z = np.dot(W, X.T) + b
  A = sigmoid(Z)
  
  cost = (- 1 / data_number) * np.sum(y * np.log(A) + (1 - y) * (np.log(1 - A)))
  
  return A, cost

In [0]:
def backward_propagation(X, A, y):
  data_number = X.shape[0]
  dW = (1 / data_number) * np.dot((A - y), X)
  db = (1 / data_number) * np.sum(A - y)
  
  return dW, db

In [0]:
def optimize(W, b, X, y, num_iterations, learning_rate):
  costs = []
  
  for i in range(num_iterations):
    A, cost = forward_propagation(W, b, X, y)
    dW, db = backward_propagation(X, A, y)
    
    W = W - learning_rate * dW
    b = b - learning_rate * db
    
    if i % 100 == 0:
      costs.append(cost)
      print ("Costo e iteracion %i: %f" % (i, cost))
    
  params = {
    "W": W,
    "b": b
  }
    
  gradients = {
    "dW": dW,
    "db": db
  }
    
  return params, gradients, costs

In [0]:
def predict(W, b, X):
  data_number = X.shape[0]
  y_prediction = np.zeros((1, data_number))
  
  Z = np.dot(W, X.T) + b
  A = sigmoid(Z)
    
  for i in range(A.shape[1]):
    y_prediction[0, i] = 1 if A[0, i] > 0.5 else 0
   
  return y_prediction

In [0]:
def model(X_train, y_train, X_val, Y_val, num_iterations=2000, learning_rate=0.5):
  dimensions = X.shape[1]
  W = np.zeros(shape=(1, dimensions))
  b = 0
  
  params, gradients, costs = optimize(W, b, X_train, y_train, num_iterations, learning_rate)

  W = params["W"]
  b = params["b"]

  y_prediction_validation = predict(W, b, X_val)
  y_prediction_train = predict(W, b, X_train)

  print("train accuracy: {} %".format(100 - np.mean(np.abs(y_prediction_train - y_train)) * 100))
  print("test accuracy: {} %".format(100 - np.mean(np.abs(y_prediction_validation - y_val)) * 100))

In [0]:
train_test_split(X, y, random_state=0, test_size=0.20)

[array([[8.27423168e-03, 1.77304965e-01, 9.21985816e-02, ...,
         4.16075650e-02, 8.17966903e-04, 6.38297872e-02],
        [4.72813239e-03, 1.14657210e-01, 7.09219858e-02, ...,
         3.33333333e-02, 5.23640662e-04, 2.60047281e-02],
        [0.00000000e+00, 1.95035461e-01, 1.06382979e-01, ...,
         6.18203310e-02, 5.04728132e-04, 2.71867612e-02],
        ...,
        [4.72813239e-03, 1.11111111e-01, 7.68321513e-02, ...,
         2.91962175e-02, 1.74940898e-04, 2.48226950e-02],
        [1.30023641e-02, 1.00472813e-01, 8.74704492e-02, ...,
         3.55791962e-02, 3.54609929e-04, 4.13711584e-02],
        [5.91016548e-03, 1.60756501e-01, 9.69267139e-02, ...,
         0.00000000e+00, 7.56501182e-04, 8.15602837e-02]]),
 array([[1.18203310e-03, 2.35224586e-01, 8.98345154e-02, ...,
         5.07092199e-02, 1.64775414e-03, 2.60047281e-02],
        [2.36406619e-03, 1.26477541e-01, 8.74704492e-02, ...,
         3.97163121e-02, 4.77541371e-04, 2.71867612e-02],
        [4.72813239e-03, 

In [0]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=0, test_size=0.20)

In [0]:
model(X_train, y_train, X_val, y_val, num_iterations = 100000, learning_rate = 0.003)

Costo e iteracion 0: 0.693147
Costo e iteracion 100: 0.687603
Costo e iteracion 200: 0.682854
Costo e iteracion 300: 0.678784
Costo e iteracion 400: 0.675295
Costo e iteracion 500: 0.672302
Costo e iteracion 600: 0.669732
Costo e iteracion 700: 0.667524
Costo e iteracion 800: 0.665626
Costo e iteracion 900: 0.663992
Costo e iteracion 1000: 0.662585
Costo e iteracion 1100: 0.661371
Costo e iteracion 1200: 0.660322
Costo e iteracion 1300: 0.659416
Costo e iteracion 1400: 0.658631
Costo e iteracion 1500: 0.657951
Costo e iteracion 1600: 0.657360
Costo e iteracion 1700: 0.656846
Costo e iteracion 1800: 0.656398
Costo e iteracion 1900: 0.656006
Costo e iteracion 2000: 0.655663
Costo e iteracion 2100: 0.655362
Costo e iteracion 2200: 0.655098
Costo e iteracion 2300: 0.654864
Costo e iteracion 2400: 0.654657
Costo e iteracion 2500: 0.654472
Costo e iteracion 2600: 0.654308
Costo e iteracion 2700: 0.654161
Costo e iteracion 2800: 0.654028
Costo e iteracion 2900: 0.653909
Costo e iteracion 3000